/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first1;

public class App {
  public String getGreeting() {
    return "Hello";
  }

  public static void main(String[] args) {
    // Load database driver in memory

    Student st = new Student();
    st.setId(10);
    st.setName("demo");
    StudImpl ob;
    ob = new StudImpl();
    ob.update(st);

  }

}
